### ISSUE TITLE
Exporting after scaling writes 'integrated.mtz'

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#101]
This has confused several people, including me.

**Comment by dagewa** [comment]
This was my fault, in that I asked for the change that introduced the automatically named scaled.mtz to be reverted in case it caused ccp4i2 to choke. In fact, it appears this is not the case. i2 will pick up whatever MTZs are produced during the DUI session.

**Comment by dagewa** [comment]
Agreed on 11/12 that this should be fixed before the Thailand workshop

**Comment by ndevenish** [comment]
This still appears to be happening? People on bag training seemed to run into this

**Comment by dagewa** [comment]
Seems to work for me today
